// Mock data for development - remove once Supabase is connected
import type { GameWithTeams, School, Sport } from '@/types/database'

export const mockSchools: School[] = [
  {
    id: '1',
    name: 'Kahuku High School',
    short_name: 'Kahuku',
    mascot: 'Red Raiders',
    island: 'Oahu',
    league: 'OIA',
    division: 'Open',
    colors: { primary: '#CC0000', secondary: '#000000' },
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Mililani High School',
    short_name: 'Mililani',
    mascot: 'Trojans',
    island: 'Oahu',
    league: 'OIA',
    division: 'Open',
    colors: { primary: '#000080', secondary: '#FFD700' },
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Saint Louis School',
    short_name: 'Saint Louis',
    mascot: 'Crusaders',
    island: 'Oahu',
    league: 'ILH',
    division: 'Open',
    colors: { primary: '#0000FF', secondary: '#FFFFFF' },
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Punahou School',
    short_name: 'Punahou',
    mascot: 'Buffanblu',
    island: 'Oahu',
    league: 'ILH',
    division: 'Open',
    colors: { primary: '#003366', secondary: '#FFCC00' },
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Kamehameha Schools',
    short_name: 'Kamehameha',
    mascot: 'Warriors',
    island: 'Oahu',
    league: 'ILH',
    division: 'Open',
    colors: { primary: '#00008B', secondary: '#FFFFFF' },
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Campbell High School',
    short_name: 'Campbell',
    mascot: 'Sabers',
    island: 'Oahu',
    league: 'OIA',
    division: 'Open',
    colors: { primary: '#FFD700', secondary: '#000000' },
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Kapolei High School',
    short_name: 'Kapolei',
    mascot: 'Hurricanes',
    island: 'Oahu',
    league: 'OIA',
    division: 'Open',
    colors: { primary: '#FF0000', secondary: '#000000' },
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Lahainaluna High School',
    short_name: 'Lahainaluna',
    mascot: 'Lunas',
    island: 'Maui',
    league: 'MIL',
    division: 'Division I',
    colors: { primary: '#800000', secondary: '#FFFFFF' },
    created_at: new Date().toISOString(),
  },
]

export const mockSports: Sport[] = [
  {
    id: '1',
    name: 'Football',
    code: 'football',
    periods_config: {
      count: 4,
      names: ['Q1', 'Q2', 'Q3', 'Q4'],
      type: 'timed',
      period_length_minutes: 12,
      overtime: { type: 'kansas', description: 'Kansas Plan - teams alternate from 10-yard line' }
    },
    season: 'fall',
    active: true,
    gender: 'boys',
    display_name: 'Football',
    sort_order: 1,
  },
  {
    id: '2',
    name: 'Basketball',
    code: 'boys-basketball',
    periods_config: {
      count: 4,
      names: ['Q1', 'Q2', 'Q3', 'Q4'],
      type: 'timed',
      period_length_minutes: 8,
      overtime: { type: 'periods', period_length_minutes: 4, unlimited: true }
    },
    season: 'winter',
    active: true,
    gender: 'boys',
    display_name: 'Boys Basketball',
    sort_order: 3,
  },
  {
    id: '3',
    name: 'Volleyball',
    code: 'girls-volleyball',
    periods_config: {
      count: 5,
      names: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      type: 'sets',
      points_to_win: 25,
      points_to_win_final: 15,
      win_by: 2,
      overtime: null
    },
    season: 'fall',
    active: true,
    gender: 'girls',
    display_name: 'Girls Volleyball',
    sort_order: 2,
  },
  {
    id: '4',
    name: 'Baseball',
    code: 'baseball',
    periods_config: {
      count: 7,
      names: ['1', '2', '3', '4', '5', '6', '7'],
      type: 'innings',
      overtime: { type: 'extra_innings' }
    },
    season: 'spring',
    active: true,
    gender: 'boys',
    display_name: 'Baseball',
    sort_order: 7,
  },
  {
    id: '5',
    name: 'Soccer',
    code: 'boys-soccer',
    periods_config: {
      count: 2,
      names: ['1st Half', '2nd Half'],
      type: 'timed',
      period_length_minutes: 40,
      overtime: { type: 'golden_goal', periods: 2, period_length_minutes: 10, playoff_only: true }
    },
    season: 'winter',
    active: true,
    gender: 'boys',
    display_name: 'Boys Soccer',
    sort_order: 5,
  },
  {
    id: '6',
    name: 'Basketball',
    code: 'girls-basketball',
    periods_config: {
      count: 4,
      names: ['Q1', 'Q2', 'Q3', 'Q4'],
      type: 'timed',
      period_length_minutes: 8,
      overtime: { type: 'periods', period_length_minutes: 4, unlimited: true }
    },
    season: 'winter',
    active: true,
    gender: 'girls',
    display_name: 'Girls Basketball',
    sort_order: 4,
  },
  {
    id: '7',
    name: 'Soccer',
    code: 'girls-soccer',
    periods_config: {
      count: 2,
      names: ['1st Half', '2nd Half'],
      type: 'timed',
      period_length_minutes: 40,
      overtime: { type: 'golden_goal', periods: 2, period_length_minutes: 10, playoff_only: true }
    },
    season: 'winter',
    active: true,
    gender: 'girls',
    display_name: 'Girls Soccer',
    sort_order: 6,
  },
  {
    id: '8',
    name: 'Softball',
    code: 'softball',
    periods_config: {
      count: 7,
      names: ['1', '2', '3', '4', '5', '6', '7'],
      type: 'innings',
      overtime: { type: 'extra_innings', extra_runner: { starts_from_inning: 10, position: 'second_base' } }
    },
    season: 'spring',
    active: true,
    gender: 'girls',
    display_name: 'Softball',
    sort_order: 8,
  },
  {
    id: '9',
    name: 'Volleyball',
    code: 'boys-volleyball',
    periods_config: {
      count: 5,
      names: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
      type: 'sets',
      points_to_win: 25,
      points_to_win_final: 15,
      win_by: 2,
      overtime: null
    },
    season: 'spring',
    active: true,
    gender: 'boys',
    display_name: 'Boys Volleyball',
    sort_order: 9,
  },
]

const today = new Date()
const todayStr = today.toISOString()

export const mockGames: GameWithTeams[] = [
  // Live game
  {
    id: '1',
    sport_id: '1',
    home_team_id: '1',
    away_team_id: '2',
    scheduled_at: todayStr,
    venue: 'Kahuku High School Stadium',
    status: 'in_progress',
    current_period: 'Q3',
    time_remaining: '8:42',
    home_score: 21,
    away_score: 14,
    is_overtime: false,
    is_verified: true,
    verification_method: 'trusted',
    golden_game: true,
    game_type: 'playoff',
    overtime_count: 0,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[0],
    away_team: mockSchools[1],
    sport: mockSports[0],
  },
  // Final game with overtime
  {
    id: '2',
    sport_id: '2',
    home_team_id: '3',
    away_team_id: '4',
    scheduled_at: todayStr,
    venue: 'Saint Louis Gymnasium',
    status: 'final',
    current_period: null,
    time_remaining: null,
    home_score: 68,
    away_score: 72,
    is_overtime: true,
    is_verified: true,
    verification_method: 'majority',
    golden_game: false,
    game_type: 'regular_season',
    overtime_count: 1,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[2],
    away_team: mockSchools[3],
    sport: mockSports[1],
  },
  // Scheduled game
  {
    id: '3',
    sport_id: '1',
    home_team_id: '5',
    away_team_id: '6',
    scheduled_at: new Date(today.getTime() + 3 * 60 * 60 * 1000).toISOString(), // 3 hours from now
    venue: 'Aloha Stadium',
    status: 'scheduled',
    current_period: null,
    time_remaining: null,
    home_score: 0,
    away_score: 0,
    is_overtime: false,
    is_verified: false,
    verification_method: null,
    golden_game: false,
    game_type: 'championship',
    overtime_count: 0,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[4],
    away_team: mockSchools[5],
    sport: mockSports[0],
  },
  // Another live game
  {
    id: '4',
    sport_id: '3',
    home_team_id: '7',
    away_team_id: '8',
    scheduled_at: todayStr,
    venue: 'Kapolei High School Gym',
    status: 'in_progress',
    current_period: 'Set 3',
    time_remaining: null,
    home_score: 2,
    away_score: 0,
    is_overtime: false,
    is_verified: true,
    verification_method: 'timer',
    golden_game: false,
    game_type: 'regular_season',
    overtime_count: 0,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[6],
    away_team: mockSchools[7],
    sport: mockSports[2],
  },
  // Scheduled basketball
  {
    id: '5',
    sport_id: '2',
    home_team_id: '1',
    away_team_id: '5',
    scheduled_at: new Date(today.getTime() + 5 * 60 * 60 * 1000).toISOString(),
    venue: 'Kahuku High School Gym',
    status: 'scheduled',
    current_period: null,
    time_remaining: null,
    home_score: 0,
    away_score: 0,
    is_overtime: false,
    is_verified: false,
    verification_method: null,
    golden_game: false,
    game_type: 'regular_season',
    overtime_count: 0,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[0],
    away_team: mockSchools[4],
    sport: mockSports[1],
  },
  // Exhibition game
  {
    id: '6',
    sport_id: '5',
    home_team_id: '2',
    away_team_id: '3',
    scheduled_at: new Date(today.getTime() + 2 * 60 * 60 * 1000).toISOString(),
    venue: 'Mililani High School Field',
    status: 'scheduled',
    current_period: null,
    time_remaining: null,
    home_score: 0,
    away_score: 0,
    is_overtime: false,
    is_verified: false,
    verification_method: null,
    golden_game: false,
    game_type: 'exhibition',
    overtime_count: 0,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[1],
    away_team: mockSchools[2],
    sport: mockSports[4],
  },
  // Scrimmage game
  {
    id: '7',
    sport_id: '6',
    home_team_id: '4',
    away_team_id: '5',
    scheduled_at: todayStr,
    venue: 'Punahou Gymnasium',
    status: 'final',
    current_period: null,
    time_remaining: null,
    home_score: 45,
    away_score: 52,
    is_overtime: false,
    is_verified: false,
    verification_method: null,
    golden_game: false,
    game_type: 'scrimmage',
    overtime_count: 0,
    tournament_id: null,
    tournament_round: null,
    bracket_position: null,
    winner_advances_to: null,
    loser_drops_to: null,
    created_at: todayStr,
    updated_at: todayStr,
    home_team: mockSchools[3],
    away_team: mockSchools[4],
    sport: mockSports[5],
  },
]

// Helper to filter games
export function getGamesBySport(sportCode: string): GameWithTeams[] {
  if (sportCode === 'all') return mockGames
  return mockGames.filter((game) => game.sport.code === sportCode)
}

export function getLiveGames(): GameWithTeams[] {
  return mockGames.filter((game) => game.status === 'in_progress')
}

export function getTodayGames(): GameWithTeams[] {
  return mockGames
}

export function getGameById(id: string): GameWithTeams | undefined {
  return mockGames.find((game) => game.id === id)
}
